<?php

/**
 * Copyright © Alexandru-Manuel Carabus All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Hyva\Theme\Model\ViewModelRegistry;
use Hawksama\HyvaUsedProductNotice\ViewModel\UsedProduct;
use Hawksama\HyvaUsedProductNotice\ViewModel\AllowedHtmlTags;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\Escaper;

/**
 * @var Template $block
 * @var ViewModelRegistry $viewModels
 * @var UsedProduct $viewModel
 * @var AllowedHtmlTags $allowedHtmlTags
 * @var HeroiconsOutline $heroicons
 * @var Escaper $escaper
 */

$viewModel = $viewModels->require(UsedProduct::class);
$heroicons = $viewModels->require(HeroiconsOutline::class);
$allowedHtmlTags = $viewModels->require(AllowedHtmlTags::class)->getAllowedHtmlTags();

// phpcs:disable Generic.Files.LineLength
?>

<?php if ($viewModel->shouldShowBlock()): ?>
    <div id="used-product"
         class="flex items-center p-4 mb-4 text-yellow-800 border-t-4 border-yellow-300 bg-yellow-50 dark:text-yellow-300 dark:bg-gray-800 dark:border-yellow-800"
         role="alert">
        <div>
            <?= $heroicons->informationCircleHtml('', 28, 28, ['aria-hidden' => 'true']) ?>
        </div>
        <div class="ms-3">
            <?= $escaper->escapeHtml($viewModel->getCmsBlockContent(), $allowedHtmlTags); ?>
        </div>
    </div>
<?php endif; ?>
