<?php

/**
 * Copyright © Alexandru-Manuel Carabus All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

/** @var \Magento\Framework\Escaper $escaper */
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Hawksama\UsedProductNotice\Magewire\ConsentInfo $magewire */

?>
<div>
    <?php if (!$magewire->hidden): ?>
    <div class="flex gap-x-4">
        <div class="flex items-center">
            <div>
                <input
                    wire:model="checked"
                    id="right-of-withdrawal-consent"
                    type="checkbox" required
                />
            </div>
        </div>
        <div class="flex-1 gap-y-2">
            <label for="right-of-withdrawal-consent">
                <?= $escaper->escapeHtml(
                    __(
                        'I acknowledge that the following products have no warranty or return policy: %1',
                        implode(', ', $magewire->getProductNames())
                    )
                ) ?>
            </label>
        </div>
    </div>
    <script>
        window.addEventListener('checkout:init:evaluation', event => {
            <?php //phpcs:ignore ?>
            hyvaCheckout.evaluation.registerValidator('validateConsentForUsedProductNoticeComponent', (element, component) => {
            })
        })
    </script>
    <?php endif; ?>
</div>

